name: Auto-generate tests

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      target_dir:
        description: 'Папка для генерации'
        required: false
      target_file:
        description: 'Файл'
        required: false
      target_function:
        description: 'Функция'
        required: false
      target_class:
        description: 'Класс'
        required: false

jobs:
  generate-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate tests
        uses: Egor213/llm-test-generator-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ai_api_key: ${{ secrets.OPENAI_API_KEY }}
          project_root: '.'
          target_dir: ${{ inputs.target_dir }}
          target_file: ${{ inputs.target_file }}
          target_function: ${{ inputs.target_function }}
          target_class: ${{ inputs.target_class }}
          model: "inclusionai/ling-2.6-1t:free"
          temperature: 0.5
          base_url: "https://openrouter.ai/api/v1"
          max_generate_retries: 3
          max_fix_attempts: 4
          target_line_coverage: 60
          llm_provider: openai
          max_tokens: 1000000

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report
          path: test_analysis_report/
