name: Test Local Runner

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, Windows] 
    steps:
      - name: test
        run: |
          python C:\Diplom\Test-gen\test.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: "Egor213/Test-gen"
