name: Test Local Runner

on:
  push:
  workflow_dispatch:
    inputs:
      repo:
        description: "GitHub repository (user/repo)"
        required: true
        default: "user/repo

jobs:
  test:
    runs-on: [self-hosted, Windows] 
    steps:
      - name: test
        run: |
          python C:\Diplom\Test-gen\test.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: "Egor213/Test-gen"
